//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFinances.Website.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myfinancesEntities : DbContext
    {
        public myfinancesEntities()
            : base("name=myfinancesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Finance> Finances { get; set; }
        public virtual DbSet<CNWPayment> CNWPayments { get; set; }
        public virtual DbSet<CNWRate> CNWRates { get; set; }
        public virtual DbSet<CNWRoute> CNWRoutes { get; set; }
        public virtual DbSet<Income> Incomes { get; set; }
        public virtual DbSet<Reminder> Reminders { get; set; }
        public virtual DbSet<Spending> Spendings { get; set; }
    }
}
