//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFinances.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNWPayment
    {
        public int Id { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public int Routes { get; set; }
        public decimal CalcMiles { get; set; }
        public Nullable<decimal> CalcSupportMiles { get; set; }
        public decimal CalcRoutePay { get; set; }
        public decimal CalcMileagePay { get; set; }
        public Nullable<decimal> CalcSupportPay { get; set; }
        public Nullable<int> CalcSupportDrops { get; set; }
        public Nullable<decimal> CalcSupportMileagePay { get; set; }
        public Nullable<decimal> CalcNetAmount { get; set; }
        public decimal CalcTotalPay { get; set; }
        public Nullable<decimal> ActualMiles { get; set; }
        public Nullable<decimal> ActualRoutePay { get; set; }
        public Nullable<decimal> ActualSupportPay { get; set; }
        public Nullable<decimal> ActualTotalPay { get; set; }
        public decimal AverageMpg { get; set; }
        public decimal AverageFuelCost { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<int> WeekNo { get; set; }
        public System.DateTime WeekDate { get; set; }
        public decimal DeduVanRental { get; set; }
        public decimal DeduAdminFee { get; set; }
        public decimal DeduVanFines { get; set; }
        public decimal DeduVanDamages { get; set; }
        public decimal DeduFuel { get; set; }
        public Nullable<decimal> Byod { get; set; }
        public string Info { get; set; }
    }
}
