//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFinances.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNWRoute
    {
        public int Id { get; set; }
        public Nullable<int> WeekNo { get; set; }
        public int RouteTypeId { get; set; }
        public System.DateTime RouteDate { get; set; }
        public Nullable<decimal> Mileage { get; set; }
        public Nullable<decimal> Mpg { get; set; }
        public Nullable<int> ExtraDrops { get; set; }
        public Nullable<decimal> ExtraMileage { get; set; }
        public string Info { get; set; }
        public decimal FuelCost { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
