//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFinances.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public int Id { get; set; }
        public int SourceId { get; set; }
        public Nullable<int> SecondSourceId { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
