//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFinances.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spending
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Date { get; set; }
        public string Info { get; set; }
        public Nullable<int> CatId { get; set; }
        public bool Display { get; set; }
        public Nullable<int> SecondCatId { get; set; }
        public Nullable<int> FinanceId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Finance Finance { get; set; }
    }
}
